sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: stbsgsIKLdgwKullj4q0cJ5oMPZqMW5zMKGyo6qsctVlHj1bQPdZog1UtNeqs+Fi1VeBBe7o2V8btwhw5OM4IqPoiB+aLUb86/WdmKOtVb6Idc+8IHxKYlM9eY0gI8rLuOBSRZeiLeOwfwKMEOQXI5YiYO6Ys0fOOnkoaTNiWUHFcrrsuwwhI0ZDWrOcbPtJAaqyYbG+6kKkxxFXO1eEDnNXEPssLLSxFcrjbzlDu6KcJX64M71+CS4BocE0zTL3pHkzM+VAnTXy4JK54wC0LQN+D2NpTTYrDb7N2cRl2EKIw/IBoqIxH0Lg/NmEpava3iGxTpG3/hn/MLiwrdzgKh3rXoUYMDbaVdbuh/8rct4xmPwfTJBzqdzbGIwRJOsgIe4M39Z25O0UjZ3NYZQdFDjVrUjp9BHcZKd4vZREeaTTxXsSJSLwWdFenqIG/AUHGpDPX/dsV05V5Fa/eRq+T+YjObPO9qhjD+5SVlT0ApkA1WuibqncYM4AVxfdsDZ59qaPy92fBsqmLPHkfcdNF525juUqCwq+jb8Mobw04ha4mC59r24qoz7TeAuscLXCLT9+MZE+M9CIFW8j7z1BEjeARHONzIHS9ekVUA93gWJ2lzchb0cmpU/yRRiz2a1YNb79nIfR3BnUxET9EzEmW6SVIMBxejo1rWxQcFuNtXM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Letters-of-Pliny_2811
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy